server:
  host: "localhost"
  port: 8080
  timeout: 30s
  debug: false

database:
  host: "localhost"
  port: 5432
  name: "yubiapp"
  user: "yubiapp"
  password: "your-database-password"
  ssl_mode: "disable"

auth:
  jwt_secret: "your-jwt-secret-key-here"
  token_expiry: 24h
  refresh_token_expiry: 720h

yubikey:
  client_id: "your-yubikey-client-id"
  secret_key: "your-yubikey-secret-key"
  api_url: "https://api.yubico.com/wsapi/2.0/verify"

sms:
  provider: "twilio"  # or other supported providers
  account_sid: "your-twilio-account-sid"
  auth_token: "your-twilio-auth-token"
  from_number: "your-twilio-phone-number"

email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-app-specific-password"
  from_email: "noreply@yourdomain.com"

web:
  session_secret: "your-session-secret-key"
  cors_origins:
    - "http://localhost:3000"
    - "https://yourdomain.com" 
